Task sprint 4
aai95/yandex-ios-movie-quiz pull request #2
Opened 2022-11-15 17:16 UTC by aai95

- Import fonts and colors
- Create launch and main application screens
- Implement base application logic

2022-11-15 19:46 UTC, ABashkirova requested changes
Привет!

Приложение верно работает. 

По верстке:
1. Цвет фона главного экрана должен быть YP Black
2. Шрифты не подгрузились, можешь попробовать удалить и внимательно проделать добавление еще раз. Или найти включение таргета в инспекторе файлов у шрифта. 
3. Не смотря на то что констрейнты расставлены в точности по уроку, по макету кнопки должны быть прижаты к нижней safearea. Этот констрейнт надо добавить на главный стек. Добавление этого констрейнта может поломать отображение лейбла с вопросом (перестанет помещаться на некоторых айфонах), тут придется идти на компромисс и давать лейблу больше пространства (уменьшить значения отступов). 

Это все что нужно исправить. 
<img width="505" alt="Снимок экрана 2022-11-15 в 23 43 08" src="https://user-images.githubusercontent.com/20269264/202011016-cae0d3d3-79d3-4853-9e5d-17ab35d135cf.png">

2022-11-15 19:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
Если возможно, используй краткую форму синтаксиса:

```suggestion
        present(alert, animated: true, completion: nil)
```

2022-11-15 19:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
свойства cornerRadius masksToBounds можно настроить один раз

2022-11-17 17:17 UTC, aai95 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.present(alert, animated: true, completion: nil)
Done

2022-11-17 17:17 UTC, aai95 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
Moved to `viewDidLoad()`

2022-11-22 13:47 UTC, merged